version: "3.8"

services:
  db:
    image: arangodb
    volumes:
      - ../.local/database:/var/lib/arangodb3
      - ../.local/database-apps:/var/lib/arangodb3-apps
    environment:
      - ARANGO_ROOT_PASSWORD=test
    ports:
      - "8529:8529"
    networks:
      net:
        aliases:
          - db

networks:
  net:
